name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_DIR="pr-${PR_NUMBER}"

          if [ -d "${PR_DIR}" ]; then
            echo "Removing preview directory: ${PR_DIR}"
            rm -rf "${PR_DIR}"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "🧹 Remove PR #${PR_NUMBER} preview"
            git push
          else
            echo "Preview directory ${PR_DIR} not found, nothing to clean up"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '🧹 Preview deployment has been cleaned up.',
            });
